spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yogurt
    password: 654321
    url: jdbc:mysql://1.117.228.42:3306/yogurt?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印